<?php $items = $this->randomItems($block->dataValue('count', 3), $block->dataValue('totalItems', 1000), $block->dataValue('show_res_template_select_option', null)); ?>
<?php $itemIds = $items[0];
      $initialItem = $items[1];
      $randomIdx = $items[2];
      $basePath = $view->basePath();
?>
<div class="item-showcase">
        <?php if ($block->dataValue('userRandom') == 1): ?>
          <button class="random-items-block-switch"><?php echo $block->dataValue('userRandomLabel', 'View Another Item') ?></button>
        <?php endif; ?>
        <div class="item resource random-item">
            <?php $media = $initialItem->primaryMedia(); ?>
            <?php if ($media): ?>
                <?php echo $this->thumbnail($media, 'large'); ?>
            <?php endif; ?>
            <h3><?php echo $initialItem->displayTitle(); ?></h3>
            <p><?php echo $initialItem->displayDescription(); ?></p>
        </div>
      <script>
        var randomItemsBlock = new RandomItemsBlock(<?php echo(json_encode($itemIds) . ',' . json_encode($randomIdx) . ',' . json_encode($basePath)); ?>);
      </script>
</div>
